# Generated by Django 2.2.4 on 2021-09-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.TextField(default='/static/master/img/logo.png'),
        ),
    ]
