# Generated by Django 2.2.4 on 2021-09-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadorbeneficio',
            name='elemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficio_trabajador_elemento', to='beneficios.ElementoBeneficio'),
        ),
    ]
