# Generated by Django 2.2.4 on 2021-09-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_auto_20210913_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='rut',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
