# Generated by Django 2.2.4 on 2021-09-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0002_elementobeneficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementobeneficio',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
