# Generated by Django 2.2.4 on 2021-09-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
